import React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  Globe, MessageCircle, Video, Music, Gamepad2, BookOpen, Briefcase, Newspaper,
  Cloud, PenTool, Heart, Code, Camera, GraduationCap, LayoutTemplate, Router,
  Wifi, Server, Database, Monitor, Smartphone, Mail, Calendar, FileText, Image,
  ShoppingCart, CreditCard, MapPin, Compass, Anchor, Zap, Flame, Sun, Moon,
  Star, Award, Tag, Key, Lock, Eye, Search, Filter, Settings, Wrench,
  Radio, Antenna, Signal, Activity, BarChart3, TrendingUp, DollarSign,
  Printer, Headphones, Mic, Speaker, Volume2, Tv, FlaskConical, Atom,
  Brain, HeartPulse, Pill, Stethoscope, Ambulance, Truck, Plane, Ship,
  Train, Car, Bike, Mountain, TreePine, Flower2, CloudRain, CloudSun, Wind,
  Thermometer, Droplets, Snowflake, Lightbulb, Battery, Cpu, HardDrive,
  Keyboard, Mouse, Joystick, Disc, Film, Clapperboard, Bookmark, Library,
  Receipt, FileCheck, FileCode, Folder, Archive, RefreshCw, Scissors, Copy,
  Clipboard, Pin, Paperclip, Link2, Share2, Send, Upload, Download, Inbox,
  MailOpen, MessageSquare, MessagesSquare, Bell, BellRing, User, Users,
  UserPlus, UsersRound, IdCard, BadgeCheck, Crown, Gem, Gift, Package, Box,
  Boxes, Warehouse, Store, ShoppingBag, Shirt, Watch, Glasses, Home, Building,
  Building2, Landmark, Factory, Hospital, School, Tent, Trees, Leaf, Recycle,
  Globe2, Map, Navigation, Locate, LocateFixed, Crosshair, Target, Siren,
  AlertTriangle, AlertCircle, Info, HelpCircle, CheckCircle, Circle, Square,
  Triangle, Hexagon, Octagon, Pentagon, Sparkles, PartyPopper, Cake, Candy,
  IceCream, Coffee, CupSoda, Beer, Wine, Utensils, Pizza, Salad, Beef, Fish,
  Egg, Cherry, Grape, Apple, Citrus, Carrot, Cookie, Croissant, Soup,
  Sandwich, Popcorn, Drumstick, Bot, BrainCircuit, CircuitBoard, Network,
  WifiOff, RadioReceiver, SatelliteDish, TowerControl, Shield, ShieldCheck,
  ShieldAlert, Sword, Swords, Bomb, Skull, Ghost, Cat, Dog, Bird, Bug,
  Snail, Turtle, Rabbit, Shell, Sailboat, LifeBuoy, Telescope, Orbit, Rocket,
  Satellite, Gauge, Timer, Clock, AlarmClock, Hourglass, CalendarDays,
  CalendarCheck, CalendarX, BatteryCharging, BatteryFull, BatteryMedium,
  BatteryLow, BatteryWarning, Power, PowerOff, PlugZap, Sunset, Sunrise,
  MoonStar, Cloudy, CloudFog, CloudLightning, CloudSnow, CloudDrizzle,
  CloudHail, Tornado, Waves, Umbrella, Percent, Divide, Plus, Minus, Equal,
  Calculator, Hash, AtSign, Asterisk, Quote, Type, Text, TextCursor,
  TextCursorInput, TextQuote, TextSearch, Table2, TableProperties, Kanban,
  KanbanSquare, Columns, Rows, SlidersHorizontal, SlidersVertical,
  ToggleLeft, ToggleRight, SwitchCamera, SmartphoneCharging, SmartphoneNfc,
  Contact2, ContactRound, UserCog, UserCog2, UserPen, UserRound,
  UserRoundCheck, UserRoundMinus, UserRoundPlus, UserRoundX, Group, Accessibility,
  Armchair, Bath, BedDouble, BedSingle, LampCeiling, LampDesk, LampFloor,
  LightbulbOff, Flashlight, CigaretteOff, RockingChair, AirVent, Blinds,
  DoorClosed, DoorOpen, Heater, ShowerHead, Toilet,
  UtensilsCrossed, CookingPot, ChefHat, Microwave, Refrigerator, WashingMachine,
  Aperture, Focus, ImageDown, ImageMinus, ImageOff, ImagePlay, ImagePlus,
  Images, PictureInPicture2, FlipHorizontal, FlipVertical, Palette,
  Paintbrush, Paintbrush2, PaintBucket, Pen, PenLine, Pencil, PencilLine,
  PencilRuler, Highlighter, Eraser, Wand, Wand2, Sparkles as Spark,
  Flower, TreeDeciduous, Palmtree, Sprout, Leaf as LeafIcon, GlassWater,
  Milk, Baby, Hand, HandMetal, ShoppingBasket, Medal, Trophy, ThumbsUp,
  ThumbsDown, Languages, LineChart, AreaChart, BarChart, BarChartBig,
  BarChartHorizontal, BarChartHorizontalBig, BarChart2, BarChart4, PieChart,
  TrendingDown, TrendingUpDown, Euro, PoundSterling, JapaneseYen,
  RussianRuble, IndianRupee, TurkishLira, SwissFranc, Bitcoin, Banknote,
  Wallet, Landmark as Landmrk, PiggyBank, ScanEye, Contact,
} from 'lucide-react';

export const availableIcons = [
  { name: 'Globe', icon: Globe },
  { name: 'MessageCircle', icon: MessageCircle },
  { name: 'Video', icon: Video },
  { name: 'Music', icon: Music },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Newspaper', icon: Newspaper },
  { name: 'Cloud', icon: Cloud },
  { name: 'PenTool', icon: PenTool },
  { name: 'Heart', icon: Heart },
  { name: 'Code', icon: Code },
  { name: 'Camera', icon: Camera },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'LayoutTemplate', icon: LayoutTemplate },
  { name: 'Router', icon: Router },
  { name: 'Wifi', icon: Wifi },
  { name: 'Server', icon: Server },
  { name: 'Database', icon: Database },
  { name: 'Monitor', icon: Monitor },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Mail', icon: Mail },
  { name: 'Calendar', icon: Calendar },
  { name: 'FileText', icon: FileText },
  { name: 'Image', icon: Image },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'MapPin', icon: MapPin },
  { name: 'Compass', icon: Compass },
  { name: 'Anchor', icon: Anchor },
  { name: 'Zap', icon: Zap },
  { name: 'Flame', icon: Flame },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Star', icon: Star },
  { name: 'Award', icon: Award },
  { name: 'Tag', icon: Tag },
  { name: 'Key', icon: Key },
  { name: 'Lock', icon: Lock },
  { name: 'Eye', icon: Eye },
  { name: 'Search', icon: Search },
  { name: 'Filter', icon: Filter },
  { name: 'Settings', icon: Settings },
  { name: 'Wrench', icon: Wrench },
  { name: 'Radio', icon: Radio },
  { name: 'Antenna', icon: Antenna },
  { name: 'Signal', icon: Signal },
  { name: 'Activity', icon: Activity },
  { name: 'BarChart3', icon: BarChart3 },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'DollarSign', icon: DollarSign },
  { name: 'Printer', icon: Printer },
  { name: 'Headphones', icon: Headphones },
  { name: 'Mic', icon: Mic },
  { name: 'Speaker', icon: Speaker },
  { name: 'Volume2', icon: Volume2 },
  { name: 'Tv', icon: Tv },
  { name: 'FlaskConical', icon: FlaskConical },
  { name: 'Atom', icon: Atom },
  { name: 'Brain', icon: Brain },
  { name: 'HeartPulse', icon: HeartPulse },
  { name: 'Pill', icon: Pill },
  { name: 'Stethoscope', icon: Stethoscope },
  { name: 'Ambulance', icon: Ambulance },
  { name: 'Truck', icon: Truck },
  { name: 'Plane', icon: Plane },
  { name: 'Ship', icon: Ship },
  { name: 'Train', icon: Train },
  { name: 'Car', icon: Car },
  { name: 'Bike', icon: Bike },
  { name: 'Mountain', icon: Mountain },
  { name: 'TreePine', icon: TreePine },
  { name: 'Flower2', icon: Flower2 },
  { name: 'CloudRain', icon: CloudRain },
  { name: 'CloudSun', icon: CloudSun },
  { name: 'Wind', icon: Wind },
  { name: 'Thermometer', icon: Thermometer },
  { name: 'Droplets', icon: Droplets },
  { name: 'Snowflake', icon: Snowflake },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Battery', icon: Battery },
  { name: 'Cpu', icon: Cpu },
  { name: 'HardDrive', icon: HardDrive },
  { name: 'Keyboard', icon: Keyboard },
  { name: 'Mouse', icon: Mouse },
  { name: 'Joystick', icon: Joystick },
  { name: 'Disc', icon: Disc },
  { name: 'Film', icon: Film },
  { name: 'Clapperboard', icon: Clapperboard },
  { name: 'Bookmark', icon: Bookmark },
  { name: 'Library', icon: Library },
  { name: 'Receipt', icon: Receipt },
  { name: 'FileCheck', icon: FileCheck },
  { name: 'FileCode', icon: FileCode },
  { name: 'Folder', icon: Folder },
  { name: 'Archive', icon: Archive },
  { name: 'RefreshCw', icon: RefreshCw },
  { name: 'Scissors', icon: Scissors },
  { name: 'Copy', icon: Copy },
  { name: 'Clipboard', icon: Clipboard },
  { name: 'Pin', icon: Pin },
  { name: 'Paperclip', icon: Paperclip },
  { name: 'Link2', icon: Link2 },
  { name: 'Share2', icon: Share2 },
  { name: 'Send', icon: Send },
  { name: 'Upload', icon: Upload },
  { name: 'Download', icon: Download },
  { name: 'Inbox', icon: Inbox },
  { name: 'MailOpen', icon: MailOpen },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'MessagesSquare', icon: MessagesSquare },
  { name: 'Bell', icon: Bell },
  { name: 'BellRing', icon: BellRing },
  { name: 'User', icon: User },
  { name: 'Users', icon: Users },
  { name: 'UserPlus', icon: UserPlus },
  { name: 'UsersRound', icon: UsersRound },
  { name: 'IdCard', icon: IdCard },
  { name: 'BadgeCheck', icon: BadgeCheck },
  { name: 'Crown', icon: Crown },
  { name: 'Gem', icon: Gem },
  { name: 'Gift', icon: Gift },
  { name: 'Package', icon: Package },
  { name: 'Box', icon: Box },
  { name: 'Boxes', icon: Boxes },
  { name: 'Warehouse', icon: Warehouse },
  { name: 'Store', icon: Store },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'Shirt', icon: Shirt },
  { name: 'Watch', icon: Watch },
  { name: 'Glasses', icon: Glasses },
  { name: 'Home', icon: Home },
  { name: 'Building', icon: Building },
  { name: 'Building2', icon: Building2 },
  { name: 'Landmark', icon: Landmark },
  { name: 'Factory', icon: Factory },
  { name: 'Hospital', icon: Hospital },
  { name: 'School', icon: School },
  { name: 'Tent', icon: Tent },
  { name: 'Trees', icon: Trees },
  { name: 'Leaf', icon: Leaf },
  { name: 'Recycle', icon: Recycle },
  { name: 'Globe2', icon: Globe2 },
  { name: 'Map', icon: Map },
  { name: 'Navigation', icon: Navigation },
  { name: 'Locate', icon: Locate },
  { name: 'LocateFixed', icon: LocateFixed },
  { name: 'Crosshair', icon: Crosshair },
  { name: 'Target', icon: Target },
  { name: 'Siren', icon: Siren },
  { name: 'AlertTriangle', icon: AlertTriangle },
  { name: 'AlertCircle', icon: AlertCircle },
  { name: 'Info', icon: Info },
  { name: 'HelpCircle', icon: HelpCircle },
  { name: 'CheckCircle', icon: CheckCircle },
  { name: 'Circle', icon: Circle },
  { name: 'Square', icon: Square },
  { name: 'Triangle', icon: Triangle },
  { name: 'Hexagon', icon: Hexagon },
  { name: 'Octagon', icon: Octagon },
  { name: 'Pentagon', icon: Pentagon },
  { name: 'Sparkles', icon: Sparkles },
  { name: 'PartyPopper', icon: PartyPopper },
  { name: 'Cake', icon: Cake },
  { name: 'Candy', icon: Candy },
  { name: 'IceCream', icon: IceCream },
  { name: 'Coffee', icon: Coffee },
  { name: 'CupSoda', icon: CupSoda },
  { name: 'Beer', icon: Beer },
  { name: 'Wine', icon: Wine },
  { name: 'Utensils', icon: Utensils },
  { name: 'Pizza', icon: Pizza },
  { name: 'Salad', icon: Salad },
  { name: 'Beef', icon: Beef },
  { name: 'Fish', icon: Fish },
  { name: 'Egg', icon: Egg },
  { name: 'Cherry', icon: Cherry },
  { name: 'Grape', icon: Grape },
  { name: 'Apple', icon: Apple },
  { name: 'Citrus', icon: Citrus },
  { name: 'Carrot', icon: Carrot },
  { name: 'Cookie', icon: Cookie },
  { name: 'Croissant', icon: Croissant },
  { name: 'Soup', icon: Soup },
  { name: 'Sandwich', icon: Sandwich },
  { name: 'Popcorn', icon: Popcorn },
  { name: 'Drumstick', icon: Drumstick },
  { name: 'Bot', icon: Bot },
  { name: 'BrainCircuit', icon: BrainCircuit },
  { name: 'CircuitBoard', icon: CircuitBoard },
  { name: 'Network', icon: Network },
  { name: 'WifiOff', icon: WifiOff },
  { name: 'RadioReceiver', icon: RadioReceiver },
  { name: 'SatelliteDish', icon: SatelliteDish },
  { name: 'TowerControl', icon: TowerControl },
  { name: 'Shield', icon: Shield },
  { name: 'ShieldCheck', icon: ShieldCheck },
  { name: 'ShieldAlert', icon: ShieldAlert },
  { name: 'Sword', icon: Sword },
  { name: 'Swords', icon: Swords },
  { name: 'Bomb', icon: Bomb },
  { name: 'Skull', icon: Skull },
  { name: 'Ghost', icon: Ghost },
  { name: 'Cat', icon: Cat },
  { name: 'Dog', icon: Dog },
  { name: 'Bird', icon: Bird },
  { name: 'Bug', icon: Bug },
  { name: 'Snail', icon: Snail },
  { name: 'Turtle', icon: Turtle },
  { name: 'Rabbit', icon: Rabbit },
  { name: 'Shell', icon: Shell },
  { name: 'Sailboat', icon: Sailboat },
  { name: 'LifeBuoy', icon: LifeBuoy },
  { name: 'Telescope', icon: Telescope },
  { name: 'Orbit', icon: Orbit },
  { name: 'Rocket', icon: Rocket },
  { name: 'Satellite', icon: Satellite },
  { name: 'Gauge', icon: Gauge },
  { name: 'Timer', icon: Timer },
  { name: 'Clock', icon: Clock },
  { name: 'AlarmClock', icon: AlarmClock },
  { name: 'Hourglass', icon: Hourglass },
  { name: 'CalendarDays', icon: CalendarDays },
  { name: 'CalendarCheck', icon: CalendarCheck },
  { name: 'CalendarX', icon: CalendarX },
  { name: 'BatteryCharging', icon: BatteryCharging },
  { name: 'BatteryFull', icon: BatteryFull },
  { name: 'BatteryMedium', icon: BatteryMedium },
  { name: 'BatteryLow', icon: BatteryLow },
  { name: 'BatteryWarning', icon: BatteryWarning },
  { name: 'Power', icon: Power },
  { name: 'PowerOff', icon: PowerOff },
  { name: 'PlugZap', icon: PlugZap },
  { name: 'Sunset', icon: Sunset },
  { name: 'Sunrise', icon: Sunrise },
  { name: 'MoonStar', icon: MoonStar },
  { name: 'Cloudy', icon: Cloudy },
  { name: 'CloudFog', icon: CloudFog },
  { name: 'CloudLightning', icon: CloudLightning },
  { name: 'CloudSnow', icon: CloudSnow },
  { name: 'CloudDrizzle', icon: CloudDrizzle },
  { name: 'CloudHail', icon: CloudHail },
  { name: 'Tornado', icon: Tornado },
  { name: 'Waves', icon: Waves },
  { name: 'Umbrella', icon: Umbrella },
  { name: 'Percent', icon: Percent },
  { name: 'Divide', icon: Divide },
  { name: 'Plus', icon: Plus },
  { name: 'Minus', icon: Minus },
  { name: 'Equal', icon: Equal },
  { name: 'Calculator', icon: Calculator },
  { name: 'Hash', icon: Hash },
  { name: 'AtSign', icon: AtSign },
  { name: 'Asterisk', icon: Asterisk },
  { name: 'Quote', icon: Quote },
  { name: 'Type', icon: Type },
  { name: 'Text', icon: Text },
  { name: 'TextCursor', icon: TextCursor },
  { name: 'TextCursorInput', icon: TextCursorInput },
  { name: 'TextQuote', icon: TextQuote },
  { name: 'TextSearch', icon: TextSearch },
  { name: 'Table2', icon: Table2 },
  { name: 'TableProperties', icon: TableProperties },
  { name: 'Kanban', icon: Kanban },
  { name: 'KanbanSquare', icon: KanbanSquare },
  { name: 'Columns', icon: Columns },
  { name: 'Rows', icon: Rows },
  { name: 'SlidersHorizontal', icon: SlidersHorizontal },
  { name: 'SlidersVertical', icon: SlidersVertical },
  { name: 'ToggleLeft', icon: ToggleLeft },
  { name: 'ToggleRight', icon: ToggleRight },
  { name: 'SwitchCamera', icon: SwitchCamera },
  { name: 'SmartphoneCharging', icon: SmartphoneCharging },
  { name: 'SmartphoneNfc', icon: SmartphoneNfc },
  { name: 'Contact2', icon: Contact2 },
  { name: 'ContactRound', icon: ContactRound },
  { name: 'UserCog', icon: UserCog },
  { name: 'UserCog2', icon: UserCog2 },
  { name: 'UserPen', icon: UserPen },
  { name: 'UserRound', icon: UserRound },
  { name: 'UserRoundCheck', icon: UserRoundCheck },
  { name: 'UserRoundMinus', icon: UserRoundMinus },
  { name: 'UserRoundPlus', icon: UserRoundPlus },
  { name: 'UserRoundX', icon: UserRoundX },
  { name: 'Group', icon: Group },
  { name: 'Accessibility', icon: Accessibility },
  { name: 'Armchair', icon: Armchair },
  { name: 'Bath', icon: Bath },
  { name: 'BedDouble', icon: BedDouble },
  { name: 'BedSingle', icon: BedSingle },
  { name: 'LampCeiling', icon: LampCeiling },
  { name: 'LampDesk', icon: LampDesk },
  { name: 'LampFloor', icon: LampFloor },
  { name: 'LightbulbOff', icon: LightbulbOff },
  { name: 'Flashlight', icon: Flashlight },
  { name: 'CigaretteOff', icon: CigaretteOff },
  { name: 'RockingChair', icon: RockingChair },
  { name: 'AirVent', icon: AirVent },
  { name: 'Blinds', icon: Blinds },
  { name: 'DoorClosed', icon: DoorClosed },
  { name: 'DoorOpen', icon: DoorOpen },
  { name: 'Heater', icon: Heater },
  { name: 'ShowerHead', icon: ShowerHead },
  { name: 'Toilet', icon: Toilet },
  { name: 'UtensilsCrossed', icon: UtensilsCrossed },
  { name: 'CookingPot', icon: CookingPot },
  { name: 'ChefHat', icon: ChefHat },
  { name: 'Microwave', icon: Microwave },
  { name: 'Refrigerator', icon: Refrigerator },
  { name: 'WashingMachine', icon: WashingMachine },
  { name: 'Aperture', icon: Aperture },
  { name: 'Focus', icon: Focus },
  { name: 'ImageDown', icon: ImageDown },
  { name: 'ImageMinus', icon: ImageMinus },
  { name: 'ImageOff', icon: ImageOff },
  { name: 'ImagePlay', icon: ImagePlay },
  { name: 'ImagePlus', icon: ImagePlus },
  { name: 'Images', icon: Images },
  { name: 'PictureInPicture2', icon: PictureInPicture2 },
  { name: 'FlipHorizontal', icon: FlipHorizontal },
  { name: 'FlipVertical', icon: FlipVertical },
  { name: 'Palette', icon: Palette },
  { name: 'Paintbrush', icon: Paintbrush },
  { name: 'Paintbrush2', icon: Paintbrush2 },
  { name: 'PaintBucket', icon: PaintBucket },
  { name: 'Pen', icon: Pen },
  { name: 'PenLine', icon: PenLine },
  { name: 'Pencil', icon: Pencil },
  { name: 'PencilLine', icon: PencilLine },
  { name: 'PencilRuler', icon: PencilRuler },
  { name: 'Highlighter', icon: Highlighter },
  { name: 'Eraser', icon: Eraser },
  { name: 'Wand', icon: Wand },
  { name: 'Wand2', icon: Wand2 },
  { name: 'Spark', icon: Spark },
  { name: 'Flower', icon: Flower },
  { name: 'TreeDeciduous', icon: TreeDeciduous },
  { name: 'Palmtree', icon: Palmtree },
  { name: 'Sprout', icon: Sprout },
  { name: 'LeafIcon', icon: LeafIcon },
  { name: 'GlassWater', icon: GlassWater },
  { name: 'Milk', icon: Milk },
  { name: 'Baby', icon: Baby },
  { name: 'Hand', icon: Hand },
  { name: 'HandMetal', icon: HandMetal },
  { name: 'ShoppingBasket', icon: ShoppingBasket },
  { name: 'Medal', icon: Medal },
  { name: 'Trophy', icon: Trophy },
  { name: 'ThumbsUp', icon: ThumbsUp },
  { name: 'ThumbsDown', icon: ThumbsDown },
  { name: 'Languages', icon: Languages },
  { name: 'LineChart', icon: LineChart },
  { name: 'AreaChart', icon: AreaChart },
  { name: 'BarChart', icon: BarChart },
  { name: 'BarChartBig', icon: BarChartBig },
  { name: 'BarChartHorizontal', icon: BarChartHorizontal },
  { name: 'BarChartHorizontalBig', icon: BarChartHorizontalBig },
  { name: 'BarChart2', icon: BarChart2 },
  { name: 'BarChart4', icon: BarChart4 },
  { name: 'PieChart', icon: PieChart },
  { name: 'TrendingDown', icon: TrendingDown },
  { name: 'TrendingUpDown', icon: TrendingUpDown },
  { name: 'Euro', icon: Euro },
  { name: 'PoundSterling', icon: PoundSterling },
  { name: 'JapaneseYen', icon: JapaneseYen },
  { name: 'RussianRuble', icon: RussianRuble },
  { name: 'IndianRupee', icon: IndianRupee },
  { name: 'TurkishLira', icon: TurkishLira },
  { name: 'SwissFranc', icon: SwissFranc },
  { name: 'Bitcoin', icon: Bitcoin },
  { name: 'Banknote', icon: Banknote },
  { name: 'Wallet', icon: Wallet },
  { name: 'Landmrk', icon: Landmrk },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'ScanEye', icon: ScanEye },
  { name: 'Contact', icon: Contact },
];

const iconMapByName: Record<string, LucideIcon> = {};
availableIcons.forEach(({ name, icon }) => {
  iconMapByName[name] = icon as LucideIcon;
});

export function getIconByName(name: string): React.ReactNode {
  const Icon = iconMapByName[name];
  if (Icon) {
    return React.createElement(Icon, { className: 'w-6 h-6' });
  }
  return React.createElement(Globe, { className: 'w-6 h-6' });
}
